### ISSUE TITLE
Question about test dataset.

### ISSUE THREAD

**Issue by meeio** [thuml/CDAN#1]
Thanks for the impresive work and sharing code.

I notice in your code that target data set and test data set are same.

``` python
config["data"] = {"source":{"list_path":args.s_dset_path, "batch_size":36}, \
                          "target":{"list_path":args.t_dset_path, "batch_size":36}, \
                          "test":{"list_path":args.t_dset_path, "batch_size":4}}
```

Is this common way to deal with test data in Domain Adaptation?

**Comment by caozhangjie** [comment]
Yes, it is a common evaluation protocol for many domain adaptation dataset. But for some dataset which splits the target dataset into training and test parts, we can use training part for training and test part for testing.
