### ISSUE TITLE
AlexNet Pretrained model

### ISSUE THREAD

**Issue by anonymous1computervision** [thuml/CDAN#10]
Hi,
I got the following error.

FileNotFoundError: [Errno 2] No such file or directory: './alexnet.pth.tar'

Can you please provide the **alexnet.pth.tar** file? Thanks in advanced.

**Comment by sy565612345** [comment]
I think this is the url of the pytorch pretrained alexnet model

model_urls = {
    'alexnet': 'https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth',
}

You can also refer to the github repository and the document on **torchvision**:
https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py
http://pytorch.org/docs/master/torchvision/

**Comment by tung-qle** [comment]
https://drive.google.com/uc?export=download&id=0B-7I62GOSnZ8NzVxZndDU2dYcHM
I believe this is the checkpoint he used. In fact, the torchvision version of AlexNet is worse than the original version one (from what I read, I did not experience it myself)
