### ISSUE TITLE
Quick question about visda target-set

### ISSUE THREAD

**Issue by kowshikthopalli** [thuml/CDAN#13]
Thanks for releasing your code. Impressive work and a good paper. I see that in the paper you report CDAN's result as 70% on VISDA dataset. Is it on visda's validation or test set. These two can be seen as two targets and the labels for test set is not released right.
So is 70% on the validation or after submitting your predictions on the test set to their codalab site. 

Thanks a lot

**Comment by sy565612345** [comment]
Hi,
the result is on the validation set.

**Comment by kowshikthopalli** [comment]
Thanks for answering 👍
