### ISSUE TITLE
Confusion about the data

### ISSUE THREAD

**Issue by Yikai-Wang** [thuml/CDAN#17]
I am using the provided data of [Image-clef](https://drive.google.com/file/d/0B9kJH0-rJ2uRS3JILThaQXJhQlk/view). It is a little confusing what does *"b_list.txt,  c_list.txt,  i_list.txt,  list,  p_list.txt"* means. 
From the paper I find that you use "c, i, p" for "Caltech-256, ImageNet ILSVRC 2012, Pascal VOC 2012", respectively. And I guess "b" is Bing. Just to check if I understand correctly.
Another problem is what is the difference between the files in "list" folder and the other four list files? In your readme file it seems that you are not using the files in the list folder. Is this the same setting in your paper?

**Comment by caozhangjie** [comment]
Your understanding is correct. We use b_list.txt, c_list.txt, i_list.txt, list, p_list.txt.
