### ISSUE TITLE
DANN

### ISSUE THREAD

**Issue by ECHOJANE** [thuml/CDAN#18]
Hello, there was an error when I was running the loss function of DANN. The dimensions did not match. Did you use this code when you were running DANN? I can't find DANN's code online right now.

**Comment by xiangruyimoxiaoyangyang** [comment]
> Hello, there was an error when I was running the loss function of DANN. The dimensions did not match. Did you use this code when you were running DANN? I can't find DANN's code online right now.

RuntimeError: size mismatch, m1: [128 x 512], m2: [5120 x 500] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290

I met the same question, can you sovle it?

**Comment by ECHOJANE** [comment]
yes ,you can see like this

ad_net = network.AdversarialNetwork(base_network.output(),1024)






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiangruyimoxiaoyangyang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 晚上7:42
收件人:&nbsp;"thuml/CDAN"<CDAN@noreply.github.com&gt;;
抄送:&nbsp;"妍妍妍妍妍！"<1915706988@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thuml/CDAN] DANN (#18)



 
Hello, there was an error when I was running the loss function of DANN. The dimensions did not match. Did you use this code when you were running DANN? I can't find DANN's code online right now.
  
RuntimeError: size mismatch, m1: [128 x 512], m2: [5120 x 500] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
 
I met the same question, can you sovle it?

**Comment by ECHOJANE** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"妍妍妍妍妍！"<1915706988@qq.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 晚上8:13
收件人:&nbsp;"thuml/CDAN"<reply@reply.github.com&gt;;"thuml/CDAN"<CDAN@noreply.github.com&gt;;
抄送:&nbsp;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;回复： [thuml/CDAN] DANN (#18)



yes ,you can see like this

ad_net = network.AdversarialNetwork(base_network.output(),1024)






------------------ 原始邮件 ------------------
发件人:&nbsp;"xiangruyimoxiaoyangyang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 晚上7:42
收件人:&nbsp;"thuml/CDAN"<CDAN@noreply.github.com&gt;;
抄送:&nbsp;"妍妍妍妍妍！"<1915706988@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thuml/CDAN] DANN (#18)



 
Hello, there was an error when I was running the loss function of DANN. The dimensions did not match. Did you use this code when you were running DANN? I can't find DANN's code online right now.
  
RuntimeError: size mismatch, m1: [128 x 512], m2: [5120 x 500] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
 
I met the same question, can you sovle it?

**Comment by xiangruyimoxiaoyangyang** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"妍妍妍妍妍！"<1915706988@qq.com&gt;; 发送时间:&nbsp;2019年11月25日(星期一) 晚上8:13 收件人:&nbsp;"thuml/CDAN"<reply@reply.github.com&gt;;"thuml/CDAN"<CDAN@noreply.github.com&gt;; 抄送:&nbsp;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;回复： [thuml/CDAN] DANN (#18) yes ,you can see like this ad_net = network.AdversarialNetwork(base_network.output(),1024)
> […](#)
> ------------------ 原始邮件 ------------------ 发件人:&nbsp;"xiangruyimoxiaoyangyang"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月25日(星期一) 晚上7:42 收件人:&nbsp;"thuml/CDAN"<CDAN@noreply.github.com&gt;; 抄送:&nbsp;"妍妍妍妍妍！"<1915706988@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [thuml/CDAN] DANN (#18) Hello, there was an error when I was running the loss function of DANN. The dimensions did not match. Did you use this code when you were running DANN? I can't find DANN's code online right now. RuntimeError: size mismatch, m1: [128 x 512], m2: [5120 x 500] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290 I met the same question, can you sovle it? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks! I solved the problem under your help! Best wishes!
