### ISSUE TITLE
some confusion about test results 

### ISSUE THREAD

**Issue by qih96** [thuml/CDAN#4]
Are the test10_crop and best_model used for final report results?

**Comment by caozhangjie** [comment]
We typically see the test results in the training process and find when it is stable. When it is stable, the result is regarded as the final result.

**Comment by qih96** [comment]
thanks for your reply. and whether the test10_crop is used for testing?

**Comment by caozhangjie** [comment]
In experiments, using no test10_crop shows better results.

**Comment by marinoso** [comment]
@caozhangjie If I understood correctly, you select the final results with the results obtained in the test dataset. This dataset, according to the code, corresponds to the target. Normally the labels of that set are not available, but it is still used to select the final model? Thank you

**Comment by caozhangjie** [comment]
No, it is just for testing. For cross-validation, you can refer to some transfer cross-validation method here 'Covariate shift adaptation by importance weighted cross validation'.
