### ISSUE TITLE
question about pre-process of image for alexnet 

### ISSUE THREAD

**Issue by meeio** [thuml/CDAN#7]
I notice that the pytorch version of your code implements pre-process in _pre_process.py_ all calling function [_transfrom.toTensor()_](https://github.com/thuml/CDAN/blob/master/pytorch/pre_process.py#L165), which scale range of image to [0,1].  Since your alexnet is based on [this repo](https://github.com/jiecaoyu/pytorch_imagenet), in this repo, all image are read as RGB image in range of [0, 255] before feed into alexnet. Now that the  Alexnet are pretrained with [0,255] range image, then finetuned(used as backbone) with [0.1] range image, will that hurt the performance of our algorithm?

**Comment by caozhangjie** [comment]
The repo also uses toTensor(): line 130 https://github.com/jiecaoyu/pytorch_imagenet/blob/master/networks/main.py

**Comment by meeio** [comment]
In the _main.py_:
```python
import datasets.transforms as transforms
...
    transforms.ToTensor()
```
The _ToTensor()_ function is not from pytorch, it redefined in [/datasets/transforms.py](https://github.com/jiecaoyu/pytorch_imagenet/blob/master/datasets/transforms.py#L39) which implemented as:
```python
class ToTensor(object):
    def __call__(self, pic):
        if isinstance(pic, np.ndarray):
            img = torch.from_numpy(pic)
            return img.float()
```
It not perform scaling.

**Comment by caozhangjie** [comment]
In this way, maybe you need to use his totensor
